name: Publish Production PowerShell Module

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: Amadevus/pwsh-script@v2
      with:
        script: |
          Write-Host "PowerShell setup complete"
    
    - name: Version  
      id: version  
      uses: juliansangillo/tag-version@v1  
      with:  
          production-branch: master  
          test-branch: test  
          dev-branch: develop 
        - name: Check Version
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      shell: pwsh
      run: |
        write-host "Release check"
        write-host "Release version env: $RELEASE_VERSION"
        write-host "Release version step: ${{ steps.vars.outputs.tag }}"
        if ($RELEASE_VERSION -eq "") {
          write-host "No version found in tag"
          exit 1
        }
    - name: Install dependencies
      shell: pwsh
      run: .\Install-Dependencies.ps1
    - name: Run Pester tests
      shell: pwsh
      run: Invoke-Pester -Path .\src\tests\M365.Toolkit.Tests.ps1

    - name: Update Manifests
      shell: pwsh
      run: .\Update-Manifest.ps1
    - name: Publish PowerShell Module
      shell: pwsh
      env:
        PSGALLERYAPIKEY: ${{ secrets.PSGALLERYAPIKEY }}
      run: |
        $moduleManifest = Get-Item -Path .\M365.Toolkit.psd1
        Publish-Module -Path (Split-Path -Path $moduleManifest.FullName -Parent) -NuGetApiKey "$($env:PSGALLERYAPIKEY)" -Confirm:$false -Force
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASETOKEN }}
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      with:
        tag_name: ${{ steps.vars.outputs.tag }}
        release_name: Release v${{ steps.vars.outputs.tag }}
        body: |
          This release includes the latest updates to the M365.Toolbox module.
        draft: false
        prerelease: true
